name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_PATH: .

jobs:
  static-checks:
    name: 'Static checks'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Scony/godot-gdscript-toolkit@master
    - run: gdformat --check source/
    - run: gdlint source/
  
  test:
    name: 'Godot Unit Test'
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run GUT tests
        run: |
          godot --headless --import
          godot --headless -s --path "$PWD" addons/gut/gut_cmdln.gd -gexit
