name: GUT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_PATH: .

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run GUT tests
        run: |
          godot --headless --import
          godot --headless -s --path "$PWD" addons/gut/gut_cmdln.gd -gexit
